import java.awt.Toolkit;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author samsu
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        instruction = new javax.swing.JButton();
        halloffame = new javax.swing.JButton();
        option = new javax.swing.JButton();
        aboutus = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Revenge");
        setBounds(new java.awt.Rectangle(0, 0, 1376, 739));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1376, 739));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play.png"))); // NOI18N
        play.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play_blink.png"))); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 230, 70));

        instruction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Instruction.png"))); // NOI18N
        instruction.setToolTipText("");
        instruction.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Instruction_Blink.png"))); // NOI18N
        instruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionActionPerformed(evt);
            }
        });
        getContentPane().add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 230, 70));

        halloffame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hall Of Fame.png"))); // NOI18N
        halloffame.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hall Of Fame_Blink.png"))); // NOI18N
        halloffame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halloffameActionPerformed(evt);
            }
        });
        getContentPane().add(halloffame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 230, 70));

        option.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Option.png"))); // NOI18N
        option.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Option_Blink.png"))); // NOI18N
        option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionActionPerformed(evt);
            }
        });
        getContentPane().add(option, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 395, 230, 70));

        aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/About Us.png"))); // NOI18N
        aboutus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/About Us_Blink.png"))); // NOI18N
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        getContentPane().add(aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 515, 230, 70));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit_Blink.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 635, 230, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1376, 739);
    }// </editor-fold>//GEN-END:initComponents

    private void instructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Instruction().setVisible(true);
    }//GEN-LAST:event_instructionActionPerformed

    private void halloffameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halloffameActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HallOfFame().setVisible(true);
    }//GEN-LAST:event_halloffameActionPerformed

    private void optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Option().setVisible(true);
    }//GEN-LAST:event_optionActionPerformed

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AboutUs().setVisible(true);
    }//GEN-LAST:event_aboutusActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        new Exit().setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        new loadingscreen().setVisible(true);
        new loadingscreen().t.start();
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutus;
    private javax.swing.JLabel background;
    private javax.swing.JButton exit;
    private javax.swing.JButton halloffame;
    private javax.swing.JButton instruction;
    private javax.swing.JButton option;
    private javax.swing.JButton play;
    // End of variables declaration//GEN-END:variables
}
